#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

supported_distributions:
  OS: [alpine, focal, jammy, lunar, centos, ubi9-minimal, windowsservercore-1809, nanoserver-1809, windowsservercore-ltsc2022, nanoserver-ltsc2022]
  Versions: [8, 11, 17, 21]

configurations:
  linux:
  - directory: ubuntu/lunar
    image: ubuntu:23.04
    architectures: [aarch64, arm, ppc64le, s390x, x64]
    os: ubuntu

  - directory: ubuntu/jammy
    image: ubuntu:22.04
    architectures: [aarch64, arm, ppc64le, s390x, x64]
    os: ubuntu

  - directory: ubuntu/focal
    architectures: [aarch64, arm, ppc64le, s390x, x64]
    image: ubuntu:20.04
    deprecated: 20
    os: ubuntu

  - directory: centos
    architectures: [aarch64, ppc64le, x64]
    image: centos:7
    deprecated: 20
    os: centos

  - directory: ubi/ubi9-minimal
    architectures: [aarch64, ppc64le, s390x, x64]
    image: redhat/ubi9-minimal
    os: ubi9-minimal

  alpine-linux:
  - directory: alpine
    architectures: [aarch64, x64]
    image: alpine:3.18
    os: alpine-linux

  windows:
  - directory: windows/windowsservercore-1809
    architectures: [x64]
    image: mcr.microsoft.com/windows/servercore:1809
    os: servercore

  - directory: windows/nanoserver-1809
    architectures: [x64]
    image: mcr.microsoft.com/windows/nanoserver:1809
    os: nanoserver

  - directory: windows/windowsservercore-ltsc2022
    architectures: [x64]
    image: mcr.microsoft.com/windows/servercore:ltsc2022
    os: servercore

  - directory: windows/nanoserver-ltsc2022
    architectures: [x64]
    image: mcr.microsoft.com/windows/nanoserver:ltsc2022
    os: nanoserver
